CREATE TABLE IF NOT EXISTS public.agent_commerce_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source TEXT NOT NULL DEFAULT 'mcp',
  tool_name TEXT NOT NULL,
  payment_tx_hash TEXT NULL,
  payment_amount_wei TEXT NULL,
  payment_status TEXT NOT NULL DEFAULT 'verified',
  payer_address TEXT NULL,
  external_agent TEXT NULL,
  request_ip TEXT NULL,
  user_agent TEXT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_agent_commerce_events_created_at
  ON public.agent_commerce_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_commerce_events_tool_name
  ON public.agent_commerce_events (tool_name);

CREATE INDEX IF NOT EXISTS idx_agent_commerce_events_payer_address
  ON public.agent_commerce_events (payer_address);

CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_commerce_events_payment_tx_hash
  ON public.agent_commerce_events ((lower(payment_tx_hash)))
  WHERE payment_tx_hash IS NOT NULL;

ALTER TABLE public.agent_commerce_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read agent commerce events" ON public.agent_commerce_events;
CREATE POLICY "Public can read agent commerce events"
  ON public.agent_commerce_events
  FOR SELECT
  USING (true);
